name: pingu-env-aflnet CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/Dockerfile-env-aflnet'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scripts/Dockerfile-env-aflnet'

jobs:    
  push:
    env:
      IMAGE_NAME: pingu-env-aflnet
      DOCKER_CLI_EXPERIMENTAL: enabled
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: ./scripts/build-env.sh -f aflnet -- --build-arg GITHUB_TOKEN=${{ secrets.ZDK_GH_TOKEN }}
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
